
font:
  family: "Segoe UI, Arial"
  size: 14

section_type:
  - type: email_title
    level: 1
    font_size: 20
    bold: true
    underline: true
  
  - type: heading
    level: 2
    font_size: 16
    bold: true
    underline: false
  
  - type: subheading
    level: 3
    font_size: 14
    bold: true
    underline: false
  
  - type: paragraph
    level: 4
    font_size: 12
    bold: false
    underline: false