subject: "End of Day Report"

format:
  font:
    family: "Segoe UI, Arial"
    size: 14

  section_type:
    - type: email_title
      level: 1
      bold: true
      underline: true
    
    - type: heading
      level: 2
      bold: true
      underline: false
    
    - type: subheading
      level: 3
      bold: true
      underline: false
    
    - type: paragraph
      level: 4
      bold: false
      underline: false

layout:
  sections:
    - type: email_title
      title: <INSERT BIG EMAIL TITLE NAME>

    - type: subheading
      subheadings:
        - title: "Lab:"
        - title: "Slot:"
        - title: "MC Build:"
        - title: "GS Build:"

    - type: heading
      title: "Today's Objectives:"
  
    - type: heading
      title: "TL;DR:"
    
    - type: heading
      title: "Detailed Summary:"

    - type: heading
      title: "Tomorrow's Objectives:"

    - type: heading
      level: "DRs Generated:"