subject: "End of Day Report"

layout:
  sections:
    - type: email_title
      title: <INSERT BIG EMAIL TITLE NAME>

    - type: subheading
      subheadings:
        - title: "Lab:"
          yaml_name: "lab"

        - title: "Slot:"
          yaml_name: "slot"

        - title: "MC Build:"
          yaml_name: "mc_build"

        - title: "GS Build:"
          yaml_name: "gs_build"

    - type: heading
      title: "todays_objectives"
      text: "Today's Objectives:"
  
    - type: heading
      title: "TL_DR"
      text: "TL;DR:"
    
    - type: heading
      yaml_name: "detailed_summary"
      title: "Detailed Summary:"

    - type: heading
      yaml_name: "tomorrows_objectives"
      title: "Tomorrow's Objectives:"

    - type: heading
      yaml_name: "drs_generated"
      level: "DRs Generated:"