type:
  - paragraph

lab:
  - Cool Lab

slot:
  - Slot111

mc_build:
  - BLD1.1.2

gs_build:
  - BLD1.1.3

staff:
  - Alice
  - Bob
  - Charlie

email_title:
  - A small note that goes under the email title

todays_objectives:
  - This is where objective 1 will be.
  - This is where objective 2 will live. 
  - And just because I am feeling froggy, this is where objective 3 will live.

tl_dr:
  - Things were blowing up. 
  - I wrote a bunch of DRs and I am depressed about it.
  - I haven't had enough sleep and I won't get enough tonight.

# The detailed_summary section supports bullets within text blocks
# Because of this, each text block is an object with a "text" field
detailed_summary:
  - text: VERY detailed.
    bullets:
      - text: SUB BULLETS LETS GO. I hope this works.
      - text: bullet two
      - text: bullet three
  - text: WOW this is SO detailed.
    bullets:
      - text: Sub bullet 1
      - text: sub bullet 2
        bullets:
          - text: hello one
          - text: hello two
  - text: Like fr give me a metal or something.

tomorrows_objectives:
  - obj 1
  - obj 2
  - obj3

drs_generated:
 - dr 1
 - dr 2
 - dr 3