
font:
  family: "Aptos"
  size: 14

type:
  email_title:
    level: 1
    font_size: 20
    bold: true
    underline: true

  heading:
    level: 2
    font_size: 16
    bold: true
    underline: false
  
  subheading:
    level: 3
    font_size: 14
    bold: true
    underline: false

  side_by_side_headings:
    level: 3
    font_size: 14
    bold: true
    underline: false
  
  paragraph:
    level: 4
    font_size: 12
    bold: false
    underline: false