subject: 
  title: "End of Day Report"

sections:
  email_title:
    type: email_title
    title: KF MAINENTANCE NOMINAL OPS DDT
    sub_bullets: false
    section_break: false
    content_structure: None

  env_info:
    type: side_by_side_headings
    title: "Environment Info:"
    sub_bullets: false
    section_break: true
    content_structure: table
    headings:
      lab:
        title: "Lab:"
        content_structure: None
      slot:
        title: "Slot:"
        content_structure: None
      mc_build:
        title: "MC Build:"
        content_structure: None
      gs_build:
        title: "GS Build:"
        content_structure: None
      staff:
        title: "Staff in Attendance:"
        content_structure: None

  todays_objectives:
    type: heading
    title: "Today's Objectives:"
    sub_bullets: false
    section_break: false
    content_structure: unordered list

  tl_dr:
    type: heading
    title: "TL;DR:"
    sub_bullets: false
    section_break: false
    content_structure: unordered list
  
  detailed_summary:
    type: heading
    title: "Detailed Summary:"
    sub_bullets: true
    section_break: false
    content_structure: unordered list

  tomorrows_objectives:
    type: heading
    title: "Tomorrow's Objectives:"
    sub_bullets: false
    section_break: true
    content_structure: unordered list

  drs_generated:
    type: heading
    title: "DRs Generated:"
    sub_bullets: false
    section_break: false
    content_structure: unordered list